help:
	@echo 'Usage:'
	@echo '	$$ make [action]'
	@echo
	@echo 'Example:'
	@echo '	$$ make'
	@echo '	$$ make help'
	@echo
	@echo '	$$ make install'
	@echo
	@echo '	$$ make packer-install'	
	@echo
	@echo '	$$ make packer-bootstrap'
	@echo
	@echo '	$$ make remove'
	@echo

.PHONY: help


install:
	./install.sh
.PHONY: install


packer-install:
	./packer-install.sh
.PHONY: packer-install


packer-bootstrap:
	./packer-bootstrap.sh
.PHONY: packer-bootstrap


remove:
	./remove.sh
.PHONY: remove
